# SPDX-FileCopyrightText: 2024 Pedrenrique G. Guimar√£es <pedrenriquegg@hotmail.com>
#
# SPDX-License-Identifier: MIT
[package]
name = "sturdygb-sdl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sturdygb = { path = "../core" }
sdl2 = { version = "0.36.0", features = ["bundled"] }
