# SPDX-FileCopyrightText: 2026 Pedrenrique G. Guimar√£es <pedrenriquegg@hotmail.com>
#
# SPDX-License-Identifier: MIT
[workspace]
members = ["crates/*"]
resolver = "1"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
