version = 1

[[annotations]]
path = "roms/mooneye-test-suite/**"
SPDX-FileCopyrightText = "2014-2022 Joonas Javanainen <joonas.javanainen@gmail.com>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "roms/cpu_instrs.gb"
SPDX-FileCopyrightText = "2026 Shay Green <gblargg@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "roms/gb-test-roms/**"
SPDX-FileCopyrightText = "2026 Shay Green <gblargg@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["roms/cgb-acid2.gbc", "roms/dmg-acid2.gb"]
SPDX-FileCopyrightText = "2020 Matt Currie"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["Cargo.lock"]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "MIT"
